[phases.setup]
nixPkgs = ['nodejs', 'python39']

[phases.install]
cmds = [
  'cd frontend && npm install --legacy-peer-deps',
  'cd backend && pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd frontend && npm run build']

[phases.start]
cmd = 'cd backend && python app.py'
